.github/renovate.json5

`postUpgradeTasks` won't run at all unless `allowedPostUpgradeCommands` has at least one regex defined which matches the `commands` option for `postUpgradeTasks`.

Update renovate automerge

---

.github/renovate.json5

It turns out these are only enabled for self hosted Renovate instances...

Revert postUpgradeTasks from Renovate config

---

cspell.yaml
manifest/v1alpha/slo/metrics_sumo_logic.go
manifest/v1alpha/slo/metrics_sumo_logic_test.go
sdk/test_data/client/simple_module/go.mod
sdk/test_data/client/simple_module/go.sum

Tightens sumo logic log query validation to allow timeslice operator to be used with 15,30 and 60 sec as an argument

feat: sumologic timeslice validation [PC-7427]

---

.github/scripts/release-notes.sh

Commits which had special regex characters, like square braces, were causing the `git log --grep <pattern>` to fail.
We need to interpret these as literal strings, thus `-F` flag, which as per `man git log` says:
> -F, --fixed-strings
Consider the limiting patterns to be fixed strings (don’t interpret pattern as a regular expression).

chore: Interpret git log grep pattern as literal string

---

.github/release-drafter.yml

Dependencies section, separate from Maintenance section is not really needed.

chore: Remove dependencies section from Release Drafter

---

manifest/v1alpha/agent/agent.go

We want to expose this information through the API, besides release notes and DockerHub/image repositories.
Added two fields to `Agent` status struct (as this information is dynamic and not a part of `Agent` definition.)

feat: Add fields to Agent Status showing newest available agent versions [PC-11737]

---

manifest/v1alpha/slo/metrics_honeycomb.go
manifest/v1alpha/slo/metrics_honeycomb_test.go
manifest/v1alpha/slo/metrics_validation.go
sdk/test_data/client/simple_module/go.mod
sdk/test_data/client/simple_module/go.sum

Due to changed logic when querying Honeycomb - we're changing how Honeycomb SLOs are defined, allowing now to set the attribute for `COUNT` and `CONCURRENCY` calculation methods.
`v1alpha` for SLOs is changed - Honeycomb-related code only.
Try to apply the SLO like
```yaml
- apiVersion: n9/v1alpha
kind: SLO
metadata:
displayName: count-with-attribute
name: count-with-attribute
project: honeycomb
spec:
alertPolicies: []
budgetingMethod: Occurrences
createdAt: "2023-11-14T11:02:02Z"
description: The example description
indicator:
metricSource:
kind: Direct
name: honeycomb
project: honeycomb
objectives:
- countMetrics:
good:
honeycomb:
attribute: latency.good
calculation: COUNT
incremental: false
total:
honeycomb:
attribute: latency.total
calculation: COUNT
name: objective-1
target: 0.7 …
```

feat: PC-11299 Honeycomb query batching enablers - allow setting `attribute` for `COUNT` and `CONCURRENCY` calculation methods

---

manifest/v1alpha/slo/metrics_honeycomb.go

Honeycomb integration became GA in the platform's 1.69 release, hence comment about beta state of the integration removal in this PR.

chore: PC-12175 Make honeycomb public in SDK

---

manifest/v1alpha/slo/slo.go

Expose new read only field `updatedAt` which allows to verify when a given SLO was updated.
`updatedAt` field is now included in SLO Spec. It gives information about when was the last time given SLO was updated.

feat: PC-12274 Add updatedAt to SLO Spec

---

manifest/v1alpha/slo/slo.go

Expose new read only field `CreatedBy` which allows to identify user who created a given SLO.
Move `UpdatedAt` to Status.
`UpdatedAt` field is included in SLO Status. It gives information about when was the last time given SLO was updated.
`CreatedBy` field is included in SLO Spec. It gives information about user ID who initially created a given SLO.

feat: PC-12274 PC-12009 Move updatedAt to status, add createdBy to spec

---

README.md

The previous logo was referencing the wrong asset.

chore: Update README.md logo

---

manifest/v1alpha/parser/parser.go

When decoding to concrete `manifest.Object` implementation `encoding/json` will fail to unmarshal `json.Number` into concrete float or int values.
This PR makes decoding into `json.Number` optional.

fix: Use optional JSON number decoding

---

internal/validation/rule.go
internal/validation/rule_test.go
manifest/v1alpha/slo/metrics_validation.go
manifest/v1alpha/slo/validation.go
manifest/v1alpha/slo/validation_composite_test.go
manifest/v1alpha/slo/validation_test.go
sdk/test_data/client/simple_module/go.mod
sdk/test_data/client/simple_module/go.sum

Validating if there's more than one composite objective in SLO should take precedence over objective uniqueness validation

fix: reorder objective validation rules to produce more adequate composite objective validation messages [PC-12021]

---

go.mod
sdk/test_data/client/simple_module/go.mod

Update Go to the newest major version which solves some recently reported govulncheck problems too.

chore: Update Go to 1.22

---

internal/validation/example_test.go
internal/validation/rules.go
internal/validation/rules_for_map.go
internal/validation/rules_for_slice.go

In order to move validation package to a separate library we need to first stabilize it's API.
This is the first PR in a cycle of changes required to achieve that.

feat: Stabilize validation API - When usage

---

manifest/v1alpha/alert/alert.go
manifest/v1alpha/alert/example.yaml

User can now find more details about why alert was triggered/resolved. Now alert returned via sloctl or API contains additional informations such as:
- when each condition was met for the first time
- when each condition lasts for was met
- when each condition was met for the last time
- when cooldown has started to be counted,
- what is the resolution reason (or cancelation).
Return additional information from the API.
Example response via sloctl for alert that was cancelled `sloctl get alert a706583a-153a-4d3f-8a12-2741cc09da9b -A`:
```yaml
- apiVersion: n9/v1alpha
kind: Alert
metadata:
name: a706583a-153a-4d3f-8a12-2741cc09da9b
project: azure-monitor-direct
organization: nobl9-processing-and-alerting
spec:
alertPolicy:
displayName: Fast Burn
name: fast-burn
project: …
```

PC-12164 feat: Additional alert details

---

manifest/v1alpha/slo/validation.go
manifest/v1alpha/slo/validation_composite_test.go

New SLO has elements at depth of 4:
```
objectives:
composite:
components:
objectives:
```
A list of objectives can be empty.
It may be possible that a typo is made at the highest depth (`objectives`), which results in no error, but the list being empty (while the user expects the objectives to be there).
Made the `components` list required, so that an empty array(YAML) / slice(Go) needs to be passed instead of omitted YAML property or nil slice.
None
Added unit tests, sample YAML with the issue:
```yaml
- apiVersion: n9/v1alpha
kind: SLO
metadata:
name: slo-test
project: sample-project
spec:
alertPolicies: []
budgetingMethod: Occurrences
objectives:
- displayName: Test
name: objective-1
composite:
maxDelay: 20m
objectives: # missing components parent`
- project: splunk-direct
slo: …
```

fix: PC-12544 Add validation for components list to be required (even if empty)

---

internal/cmd/docgen/main.go

Currently `docgen` only outputs yaml, which is slower to decode and weights more but it's easier to read by a human.
External tools however, would benefit more from having it in JSON than YAML.

chore: Add option to change output format to compacted JSON in docgen

---

manifest/v1alpha/slo/metrics_logic_monitor.go
manifest/v1alpha/slo/metrics_logic_monitor_test.go

Corrects invalid field names for Logic Monitor:
- `deviceDataSourceInstanceID` --> `deviceDataSourceInstanceId`
- `groupID` --> `groupId`

fix: Correct Logic Monitor validation

---

manifest/v1alpha/project/project.go

Right now there is no info for the project about when it was created and who created it. We are developing some internal APIs to manage nobl9, and would love to get this info added. 
I have added relevant fields to the `Project` struct, the core controller needs to populate these fields, but since it isn't open-source, I can't do that myself.
@nieomylnieja  Let me know your thoughts 😄 
Added `createdAt` and `createdBy` fields to v1alpha Project.
These fields are not yet populated by the API, follow our [release notes](https://docs.nobl9.com/application-release-notes) to get informed when the API support ships.

feat: add createdAt and createdBy to project

---

.github/scripts/release-notes.sh

Ignore `signed-off-by` and `co-authored-by` suffixes from commit messages while generating release notes.
Made evident by:

chore: Ignore commit suffix

---

.github/workflows/e2e-tests.yml

In CI we don't want to create a config file to store the access token, thus we need to pass additional env to SDK config.

chore: Add no config file

---

go.mod
go.sum
manifest/v1alpha/parser/parser_test.go
manifest/v1alpha/parser/test_data/cloudwatch_slo.yaml

The issue is extensively covered in this issue: https://github.com/goccy/go-yaml/issues/455
Added test case and replaced `goccy/go-yaml` with our fork.
For now I'm pinning the commit SHA from the PR branch.
I'm not sure if the upstream is actively maintained anymore, we might just want to go further with the fork instead of the replace clause.
- https://github.com/goccy/go-yaml/pull/457
- https://github.com/nobl9/go-yaml/pull/3
Test case was supplied.
Fixed incorrect handling of double quoted JSON literals which caused errors when unmarshaling CloudWatch v1alpha SLOs
with certain `json` queries.

fix: Double quoted JSON handling

---

manifest/v1alpha/alert_methods.go
manifest/v1alpha/alert_methods_enum.go
manifest/v1alpha/alertmethod/alert_method.go

Having sth like `v1alpha.Email` in the namespace is way too vague, we need more specific naming, that's why we need a prefix.

chore: Correct Alert Method type names

---

.golangci.yml
go.mod
go.sum
internal/cmd/docgen/main.go
internal/manifest/v1alphatest/labels_validation.go
internal/manifest/v1alphatest/metadata_annotations_validation.go
internal/validation/example_test.go
manifest/v1alpha/dataexport/data_export.go
manifest/v1alpha/parser/parser.go
sdk/decode.go
sdk/decode_test.go
sdk/encode.go

Modules using `nobl9-go` cannot rely on `replace` clause in the SDK if they are using `go-yaml` package as well, in such scenario these modules have to using `replace` clause too and this in turn breaks `go install`, here's an example:
```
go install github.com/nobl9/sloctl/cmd/sloctl@latest
go: downloading github.com/nobl9/sloctl v0.3.2
go: github.com/nobl9/sloctl/cmd/sloctl@latest (in github.com/nobl9/sloctl@v0.3.2):
The go.mod file for the module providing named packages contains one or
more replace directives. It must not contain directives that would cause
it to be interpreted differently than if it were the main module.
```

chore: Switch go-yaml library to Nobl9 fork

---

.github/workflows/e2e-tests-dispatch.yml
.github/workflows/e2e-tests.yml
tests/helpers_test.go
tests/v1alpha_agent_test.go
tests/v1alpha_slo_test.go

Since we're currently running into concurrency problems, we need to be able to constrain parallelism of apply/delete operations on demand.
```shell
export NOBL9_SDK_TEST_RUN_SEQUENTIAL_APPLY_AND_DELETE=true
make test/e2e
```
https://github.com/nobl9/nobl9-go/actions/runs/10095740091

chore: Allow sequential apply/delete execution for end-to-end tests

---

tests/v1alpha_dataexport_test.go

Adds v1alpha `DataExport` e2e tests.

chore: Add Data Export end-to-end tests

---

docs/DEVELOPMENT.md
internal/cmd/docgen/README.md
internal/cmd/examplegen/README.md
internal/manifest/v1alpha/examples/doc.go
internal/manifest/v1alpha/examples/example_test.go
manifest/kind.go

- Update developer docs
- Add test for making sure each new `manifest.Object` has generated examples
- Add `UserGroup` to non-applicable objects

chore: Update developer docs and examples

---

manifest/v1alpha/direct/validation.go
manifest/v1alpha/direct/validation_test.go

Removing redundant validation for `ClientID` and `ClientSecret` in Logic Monitor

fix: Removing redundant validation in LogicMonitor [PC-13783]

---

manifest/v1alpha/report/validation_system_health_review.go
manifest/v1alpha/report/validation_test.go
tests/v1alpha_report_test.go

- PC-13726 Add e2e tests for Reports
- PC-13759 Snapshot Rrule frequency lower than DAILY forbidden
- PC-13823 Snapshot date time in the future forbidden
- PC-14191 Thresholds lower than 0 allowed

feat: Add e2e tests for Reports, extend reports validation

---

manifest/v1alpha/report/validation_system_health_review.go
manifest/v1alpha/report/validation_test.go

Flaky validation for System Health Review thresholds. They are not supposed to go up to 1.
Changed validation from LTE to LT and adjusted tests.
System Health Review spec now allows for green and red thresholds to be less than 1, not less than or equal to 1.

fix: PC-14236 SHR thresholds validation for less than 1

---

internal/manifest/v1alpha/examples/slo_composite.go
manifest/v1alpha/slo/examples/composite-slo.yaml
manifest/v1alpha/slo/slo.go
sdk/test_data/reader/expected/composite_v2_slo.tpl.json

… Composite SLOs (#529)"
This reverts commit 0350ad44fc725bb176a114e1613f927ef400e04c.
Changes we introduced in #529 and https://github.com/nobl9/n9/pull/15176 are breaking API contract for older versions of SDK in a way that blocks the release. We must prepare better backward compatibility before introducing these changes.
This reverses changes introduced in #529.
#529
https://github.com/nobl9/n9/pull/15176
Changes from #529 are reverted.

fix: PC-13893 Revert changes from #529

---

tests/v1alpha_slo_test.go

`value` field of `objective` for Composite SLO is being [deprecated](https://github.com/nobl9/nobl9-go/pull/549). Before the update in SDK can be made, a N9 platform first needs to be [updated](https://github.com/nobl9/n9/pull/15406). To be able to release changes in the platform, e2e tests of the latest released SDK need to pass against it.
E2E test assertions will pass with and without [changes](https://github.com/nobl9/n9/pull/15406) in N9 platform.
https://github.com/nobl9/nobl9-go/pull/551
https://github.com/nobl9/nobl9-go/pull/549
https://github.com/nobl9/n9/pull/15406
https://github.com/nobl9/terraform-provider-nobl9/pull/312
https://github.com/nobl9/terraform-provider-nobl9/pull/295
Run `make test/e2e` on both environments containing and not containing …

test: PC-13893 Make E2E tests forward compatible

---

manifest/v1alpha/slo/slo.go
sdk/models/replay.go

Extend ReplayStatus with source and the user who triggered the Replay. 
- added fields to `v1alpha.ReplayStatus`:
-  `Source` - `user` | `composite_slo` | `error_budget_adjustment`
-  `TriggeredBy` - user okta ID
Extend `v1alpha.ReplayStatus` with source and the user who triggered the Replay.

feat: extend SLO status replay with source and user [PC-14276]

---

internal/manifest/v1alpha/validation.go
manifest/v1alpha/report/validation_system_health_review.go
manifest/v1alpha/report/validation_test.go

Add validation for System Health Review column display name for consistency with other names in the system.
Adjust System Health Review report validation.

fix: PC-14338 System Health Review report name should not be longer than 63 chars

---

tests/slostatusapi_test.go

Removed equal SLO Status API cursors tests.
https://github.com/nobl9/nobl9-go/pull/537
Removed equal SLO Status API cursors tests.

fix: PC-14087 Adjust SLO Status API tests

---

manifest/v1alpha/data_sources.go
manifest/v1alpha/data_sources_test.go

Expose `Duration` method on `v1alpha.HistoricalRetrievalDuration` struct.

feat: add Duration() to v1alpha.HistoricalRetrievalDuration

---

sdk/http_errors.go
sdk/http_errors_test.go

Corrected `APIError` decoding, it is now decoded as part of `APIErrors`. The `APIErrors` is in turn embedded into `HTTPError`.
Added `APIErrors` struct which aggregates individual `APIError` and is embedded into `HTTPError`.

feat: Add APIErrors struct

---

sdk/http_error.tmpl
sdk/http_errors.go
sdk/http_errors_test.go

Add method for a string representation of APIErrors.
https://github.com/nobl9/nobl9-go/pull/579

chore: Add Error() to APIErrors (string representation of APIErrors)

---

manifest/v1alpha/slo/metrics_lightstep.go
manifest/v1alpha/slo/metrics_lightstep_test.go

Allow the `constant` keyword in the UQL queries as there are valid use cases for constant values. 
Change validation to allow `constant` in UQL. 
- The `constant` in the UQL query should not throw validation error.
Allow the `constant` keyword in the ServiceNow Observability UQL queries.

feat: allow constant keyword in ServiceNow Obs (Lightstep) UQL queries [PC-14700]

---

manifest/v1alpha/agent/examples/elasticsearch.yaml
manifest/v1alpha/data_sources.go

Adding Replay support to Elasticsearch integration.
Adds data retrieval definitions for Elasticsearch using Agent Connection.
Since Elasticsearch cannot be conffigured via Direct connection, those definitions for direct were not changed.
Adds Replay support to Elasticsearch data source (Agent connection only).

feat: Add Replay support to Elasticsearch

---

go.mod
go.sum
manifest/v1alpha/slo/metrics_instana_test.go
manifest/v1alpha/slo/metrics_splunk.go
manifest/v1alpha/slo/metrics_splunk_test.go
manifest/v1alpha/slo/metrics_validation.go
manifest/v1alpha/slo/validation.go
manifest/v1alpha/slo/validation_test.go

The CountMetrics validation was missing a case when only one metric was provided. It was failing with an error on our backend but cusomers didn't get a good error - it already tripped one of our customers.
- Extended unit tests
- Can be tested by applying an SLO with for example only total.
Fixed `v1alpha.SLO.Spec.Objectives[*].CountMetrics` validation for cases when only one metric was provided.

fix: CountMetrics validation

---

manifest/v1alpha/alertmethod/notification_template.go

Added possibility to use in Webhook alert method new template variable `alert_id` which indicates a unique alert  generated by Nobl9.
Possibility to pass `alert_id` via Webhook alert method.
Added `alert_id` as possible template variable.

feat: Extend list of alert method template variables with `alert_id`

---

internal/manifest/v1alpha/examples/agent.go
manifest/v1alpha/agent/examples/elasticsearch.yaml

Replay support has been added to Elasticsearch only on BETA channels. This configuration implies the use of Historical Retrieval defaults and max durations, which are only available on BETA.
Use Beta Elasticsearch in e2e tests.
Run `Test_Objects_V1_V1alpha_Agent` on any environment

fix: Use beta elasticsearch in tests

---

internal/manifest/v1alpha/examples/alert_method.go
manifest/v1alpha/alertmethod/alert_method.go
manifest/v1alpha/alertmethod/examples/email.yaml

Fields are no longer used since July 2024. Those fields are not used anywhere in the application since then.
Removed deprecated fields Subject and Body from Email alert method. Those fields are not used in application since July 2024 (see https://github.com/nobl9/nobl9-go/releases/tag/v0.18.0)
- https://github.com/nobl9/nobl9-go/releases/tag/v0.18.0
Removed deprecated fields Subject and Body from Email alert method.

chore: Remove deprecated Body and Subject from Email alert method

---

manifest/v1alpha/alertmethod/alert_method.go

Those fields are not needed anymore. Alert method `Status` section contains only timestamps when alert method was tested on UI, which is handled in another way. Those fields are not used anymore.
Removed `Status` section from kind `AlertMethod`.
Removed `Status` section from kind `AlertMethod`.

chore: Remove Status from kind AlertMethod

---

cspell.yaml
manifest/v1alpha/slo/metrics.go
manifest/v1alpha/slo/metrics_test.go
manifest/v1alpha/slo/slo.go

In certain cases we want to include query validation status per objective in SLO status itself.
This PR adds `QueryValidationStatus` definition to kind SLO `status` field. For now, it's availability will be limited in the API.
Add `QueryValidationStatus` definition to kind SLO `status` field.

feat: PC-14959 Extend kind SLO with QueryValidationStatus

---

.golangci.yml
Makefile
tests/helpers_test.go
tests/main_test.go
tests/v1alpha_alertmethod_test.go
tests/v1alpha_annotation_test.go
tests/v1alpha_direct_test.go
tests/v1alpha_slo_test.go

The linter was not detecting problems with files tagged by `e2e_test`.
This PR fixes that, it also adds these tags to `go vet` invocation and addresses issues reported by the linter on these files.

chore: Update golangci linter config

---

tests/v1alpha_slo_test.go

E2E tests are failing because we recently introduced a change the behavior of API regarding a `value` field in composite SLO objective. Before that change, there was an update to make a test assertion forward-compatible. We forgot to remove that change in the test when merging an actual change.
Updated test assertion for the new behavior.
https://github.com/nobl9/nobl9-go/pull/549
https://github.com/nobl9/nobl9-go/pull/551

fix: E2E tests are failing for composite SLOs

---

manifest/v1alpha/slo/metrics_validation.go
manifest/v1alpha/slo/validation.go
manifest/v1alpha/slo/validation_test.go

When an SLO is defined with missing metric spec for either count or raw metrics, the SDK validation will now return an error.

fix: Adjust validation for missing metric spec [PC-15176]

---

sdk/reader.go
sdk/source.go

It can be unclear how the `sdk.ObjectSourceTypeURL` is interpreted, we should make the constraints it operates within clear.
Improved linking of the Go docs.

chore: Improve sdk.ReadObjects docs [PC-15261]

---

internal/serdeutil/raw_message.go
internal/testutils/assert.go
manifest/doc.go
manifest/format.go
manifest/kind.go
manifest/object.go
manifest/v1alpha/labels.go
manifest/v1alpha/parser/parser_test.go
manifest/version.go
sdk/client.go
sdk/config.go
sdk/config_file.go
sdk/credentials.go
sdk/credentials_test.go
sdk/decode.go
sdk/endpoints/authdata/v1/endpoints.go
sdk/http.go
sdk/jwt.go
sdk/models/replay.go
sdk/reader.go
sdk/source.go

A lot of the Go code docs has invalid code links, there are also formatting issues with lists.

chore: Correct Go code docs - fix links

---

manifest/v1alpha/slo/slo.go
sdk/models/replay.go

With replay queues we now save end time to be more precise than Duration (as a replay can wait in queue before it is started).
Changed ReplayStatus and ProcessStatus structs
Test in sloctl and in UI.
End time is now returned for new replays in progress and finished.

feat: PC-15221 Add EndTime to replay

---

manifest/v1alpha/alertmethod/validation.go
manifest/v1alpha/alertmethod/validation_opsgenie_test.go
manifest/v1alpha/alertmethod/validation_slack_test.go
manifest/v1alpha/alertmethod/validation_test.go

Described in [PC-9592 ](https://nobl9.atlassian.net/browse/PC-9592)
Added validation for opsgenie and slack URLs, the validation is the same as the validation in corresponding notifications services:
* [opsgenie](https://github.com/nobl9/n9/blob/main/notifications/notificationsopsgenie/internal/notifier/notificationsopsgenie.go#L92)
* [slack](https://github.com/nobl9/n9/blob/main/notifications/notificationsslack/internal/notifier/notificationsslack.go#L83)
None
-  Added unit tests
Improved URL validation for Opsgenie and Slack alert methods:
* Slack URLs must now begin with `https://hooks.slack.com/services/`.
* Opsgenie URLs must start with either `https://api.opsgenie.com` or `https://api.eu.opsgenie.com`.

fix: PC-9592 Validate opsgenie and slack URLs at submission

---

Makefile
manifest/v1alpha/report/validation_slo_history.go
manifest/v1alpha/report/validation_test.go

Corrected paths reported by object's validation for Report kind under `spec.sloHistory.timeFrame`.

fix: Correct Report timeFrame paths

---

manifest/v1alpha/budgetadjustment/validation.go
manifest/v1alpha/budgetadjustment/validation_test.go

Due to customer question we have to set duration precision to one second with minimum one minute limit.

feat: PC-14241 budget adjustment spec duration should not have precision set to 1 m

---

internal/manifest/v1alpha/examples/report.go
internal/manifest/v1alpha/examples/slo_composite.go
manifest/v1alpha/report/report.go
manifest/v1alpha/report/system_health_review.go
manifest/v1alpha/report/validation_system_health_review.go
manifest/v1alpha/report/validation_test.go
manifest/v1alpha/report/validation_time_frame.go
tests/v1alpha_report_test.go
tests/v1alpha_slo_test.go

Report object was redefining `v1alpha.Labels` instead of using it.
Fixed some minor issues reported by _gopls_.
`report.Labels`, `report.LabelKey` and `report.LabelValue` have been removed, use `v1alpha.Labels` instead.

fix: Correct labels usage in Report object

---

internal/manifest/v1alphatest/metadata_annotations_validation.go
manifest/v1alpha/metadata_annotations.go

`v1alpha.MetadataAnnotations` now allows upper case characters in keys.

feat: Relax MetadataAnnotations validation

---

manifest/v1alpha/slo/slo.go
sdk/test_data/reader/expected/composite_v2_slo.tpl.json
sdk/test_data/reader/expected/slo.tpl.json

While our API always returns an empty list if no alert policies were provided, when programatically creating an SLO the resulting YAML/JSON encoding is produced with `null` value for empty policies.
SLO field `spec.alertPolicies` will no longer produce `null` value when encoding to JSON or YAML, instead, if empty (nil) it will be skipped.

chore: Add omitempty tag to SLO alertPolicies

---

tests/v1alpha_slo_test.go

Changes introduced in https://github.com/nobl9/nobl9-go/pull/679 have caused these tests to fail.
Tests dispatch: https://github.com/nobl9/nobl9-go/actions/runs/14490771847

chore: Correct end-to-end tests for v1alpha SLO

---

go.mod
go.sum
sdk/encode_test.go

Pinned the `go-yaml` version until https://github.com/goccy/go-yaml/pull/698 is released.
Fixes segmentation violation errors when `apiVersion` was set to an empty string in any of the v1alpha objects.

fix: Solve segmentation violation errors for empty APIVersion [PC-16865]

---

go.mod

It turns out that:
> replace directives only apply in the main module’s go.mod file and are ignored in other modules
So it seems this directive is ignored when using nobl9-go in other projects.

fix: Remove replace directive for go-yaml and set it directly

---

internal/manifest/v1alpha/examples/agent.go
internal/manifest/v1alpha/examples/direct.go
manifest/v1alpha/agent/examples/thousand-eyes.yaml
manifest/v1alpha/direct/examples/thousand-eyes.yaml
tests/v1alpha_agent_test.go

Update end-to-end tests after adding historical data retrieval settings to ThousandEyes Agent and Direct types.
https://github.com/nobl9/nobl9-go/pull/715

chore: fix v1alpha.Agent and v1alpha.Direct e2e tests [PC-16874]

---

sdk/client_test.go
sdk/config.go
sdk/config_test.go

Currently it's hard to tell if file config has been loaded or not.
This PR changes the `GetFileConfig`contract to return a nil pointer if no file config was loaded.
Previously, the function was returning only a shallow copy of `FileConfig`, now it returns a proper deep copy.
`sdk.Config.GetFileConfig` now returns a pointer.

feat: Improve FileConfig handling

---

manifest/v1alpha/service/example_test.go
manifest/v1alpha/service/service.go
manifest/v1alpha/service/validation.go
manifest/v1alpha/service/validation_test.go

Add `reviewCycle` to Service kind spec.
This pull request introduces a new `ReviewCycle` feature for services, enabling the specification and validation of recurring review schedules. The changes span the addition of new fields, validation logic, and comprehensive test cases to ensure correctness.
* **Definition of `ReviewCycle`:**
- Added a new `ReviewCycle` struct to define recurring review schedules with fields for `StartTime`, `TimeZone`, and `RRule`. (`manifest/v1alpha/service/service.go`, [manifest/v1alpha/service/service.goR48-R73](diffhunk://#diff-38c42076c670a2a2528ffa147c38baedafa53df7b5e71fc8d218931f7988b483R48-R73))
- Introduced a corresponding `ReviewCycleStatus` struct to track the dynamic status of review cycles, including `Next` and `Previous` review dates. …

feat: service review cycle

---

manifest/v1alpha/slo/validation.go
manifest/v1alpha/slo/validation_composite_test.go

Hardened validation for instances when `rawMetric` or `countMetrics` was provided with `composite` section in the `spec.objective` definition.

fix: correct validation for composite SLOs

---

manifest/v1alpha/slo/slo.go
sdk/endpoints/objects/v1/slos/review/review.go

Add `not_started` status to submit Review payload definition.

chore: add not_started status to SLO Review

---

internal/manifest/v1alpha/slo/slo.go
manifest/v1alpha/examples/slo.go
manifest/v1alpha/examples/slo_variants.go
manifest/v1alpha/slo/examples/sumo-logic.yaml
manifest/v1alpha/slo/metrics_sumo_logic.go
manifest/v1alpha/slo/metrics_sumo_logic_test.go
manifest/v1alpha/slo/metrics_validation.go
manifest/v1alpha/slo/validation_test.go

In order to better align good and total values returned from the SumoLogic API and improve rate limiting constraints we're adding single query support.
This update introduces support for SumoLogic single-query good-over-total metrics. Changes include:
- Added `SumoLogic` to the list of supported data sources for single-query good-over-total metrics.
- Updated the `generateMetricVariant` function to handle the new metric variant for SumoLogic logs.
- Refactored SumoLogic logs validation logic to support single-query metrics, introducing a new `getSumoLogicLogsTypeValidation` function.
- Enhanced validation rules to ensure proper query structure for single-query metrics, including checks for `n9_good`, `n9_total`, and `timeslice` usage.
- Added comprehensive test cases to validate both …

feat: add support for SumoLogic single-query good-over-total metrics [PC-17863]
