.github/release-drafter.yml
=> chore: Add Release Drafter config

.github/renovate.json5
=> chore: Update Renovate with automerge

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
Fixed two issue template typos.
=> chore: Fix issue template typos

manifest/v1alpha/slo/composite.go, manifest/v1alpha/slo/composite_test.go, manifest/v1alpha/slo/test_data/expected_string_is_dns_subdomain_error.txt, manifest/v1alpha/slo/validation.go, manifest/v1alpha/slo/validation_composite_test.go, manifest/v1alpha/slo/validation_test.go
Added more validation and tests according to specification
Validation for `kind.SLO`
=> feat: PC-12012 Composite SLO validation

docs/DEVELOPMENT.md
=> doc: Update DEVELOPMENT.md

README.md
Update Nobl9 logo to the new one.
=> chore: Update Nobl9 logo

manifest/v1alpha/slo/slo.go
Recent changes introduced regression.
=> fix: Bring back createdBy and remove duplicate updatedAt

manifest/v1alpha/slo/slo.go, manifest/v1alpha/slo/validation.go, manifest/v1alpha/slo/validation_test.go
Expose new field `primary` to highlight a specific objective in an SLO.
=> feat: PC-11745 Add Primary to Objective

sdk/client.go, sdk/credentials.go
We are writing an internal API where we need to retrieve current user for nobl9. Now, since it is not exposed outside the module, there was no better way to do this. Someone else might need this as well.
adds a `GetUser` func which returns user
Added `GetUser` method for `Client` which returns the current session user read from JWT token.
=> feat: add GetUser() to return current user

manifest/v1alpha/annotation/annotation.go, manifest/v1alpha/annotation/validation.go, manifest/v1alpha/annotation/validation_test.go
We have introduced category field for annotations created by our system (for alerts and budget adjustments) to differentiate between them in our UI and also later yamls.
=> feat: PC-10331 Add annotation category

manifest/v1alpha/data_sources.go
Adds Replay support to Google Cloud Monitoring.
Adds GCM to Agent and Direct max duration retrieval definitions.
Adds Replay support to Google Cloud Monitoring.
=> feat: add GCM Replay support [PC-12560]

tests/v1alpha_alertsilence_test.go
Added v1alpha `AlertSilence` end-to-end tests.
=> chore: Add Alert Silence end-to-end tests

tests/helpers_test.go, tests/v1alpha_annotation_test.go
Adds v1alpha `Annotation` e2e tests.
=> chore: Add Annotations end-to-end tests

internal/manifest/v1alpha/examples/direct.go, tests/v1alpha_direct_test.go
Fix failing tests for Azure Prometheus
=> fix: Fix tests for Azure Prometheus Direct [PC-13028]

.github/renovate.json5, .github/scripts/release-notes.sh, .golangci.yml
Synced the following files:
- .golangci.yml
- .github/renovate.json5
- .github/scripts/release-notes.sh
Root repository ref: https://github.com/nobl9/go-repo-template
Pull request generated by [gitsync](https://github.com/nieomylnieja/gitsync)
=> chore: gitsync updates

docs/RELEASE.md
Remove a misleading sentence from `RELEASE.md`.
=> chore: Adjust release doc

manifest/v1alpha/slo/slo.go
Removed outdated comment about composites 2.0 being unavailable. Fixed a few other comments too.
=> chore: PC-13881 Fix comment about composites 2.0 being unavailable

internal/manifest/v1alpha/examples/slo_composite.go, manifest/v1alpha/slo/examples/composite-slo.yaml
Removed anomaly config from composite tests
=> fix: PC-13744 Removed anomaly config from composite e2e test

docs/DEVELOPMENT.md
=> chore: Update DEVELOPMENT.md

manifest/v1alpha/budgetadjustment/validation.go, manifest/v1alpha/budgetadjustment/validation_test.go
Added BudgetAdjustment validation for unique SLOs in filters
=> feat: PC-13831 unique SLOs validation and test

internal/manifest/v1alpha/examples/report.go, manifest/v1alpha/report/example_test.go, manifest/v1alpha/report/examples.yaml, manifest/v1alpha/report/validation.go, manifest/v1alpha/report/validation_slo_history.go, manifest/v1alpha/report/validation_test.go, manifest/v1alpha/report/validation_time_frame.go
Validation added to SLO History time frame options.
Validation added to SLO History time frame options.
=> feat: PC-13791 Add validation to SLO History report's time frame

tests/v1alpha_budgetadjustment_test.go
Fix broken budgetadjustments e2e tests
=> fix: Fix budget adjustments e2e tests

internal/manifest/v1alpha/examples/slo.go, internal/manifest/v1alpha/examples/slo_variants.go, manifest/v1alpha/slo/examples/thousand-eyes.yaml, manifest/v1alpha/slo/metrics_thousand_eyes.go
New test type in Thousandeyes
Added test type name
https://github.com/nobl9/nobl9-go/pull/624/files
No testing needed.
Added API Test type for Thousandeyes integration.
=> feat: Add new Thousandeyes test type - API transaction time

docs/mock_example/mocks/objects_v1.go, internal/manifest/v1alpha/examples/direct.go, manifest/v1alpha/direct/direct.go, manifest/v1alpha/direct/examples/app-dynamics.yaml, manifest/v1alpha/direct/examples/azure-monitor.yaml, manifest/v1alpha/direct/examples/azure-prometheus.yaml, manifest/v1alpha/direct/examples/big-query.yaml, manifest/v1alpha/direct/examples/cloud-watch.yaml, manifest/v1alpha/direct/examples/datadog.yaml, manifest/v1alpha/direct/examples/dynatrace.yaml, manifest/v1alpha/direct/examples/google-cloud-monitoring.yaml, manifest/v1alpha/direct/examples/honeycomb.yaml, manifest/v1alpha/direct/examples/influx-d-b.yaml, manifest/v1alpha/direct/examples/instana.yaml, manifest/v1alpha/direct/examples/lightstep.yaml, manifest/v1alpha/direct/examples/logic-monitor.yaml, manifest/v1alpha/direct/examples/new-relic.yaml, manifest/v1alpha/direct/examples/pingdom.yaml, manifest/v1alpha/direct/examples/redshift.yaml, manifest/v1alpha/direct/examples/splunk-observability.yaml, manifest/v1alpha/direct/examples/splunk.yaml, manifest/v1alpha/direct/examples/sumo-logic.yaml, manifest/v1alpha/direct/examples/thousand-eyes.yaml, manifest/v1alpha/direct/validation.go, manifest/v1alpha/direct/validation_test.go
Added `metadata.annotations` to Direct.
=> feat: Add annotations to Direct

sdk/http_errors.go, sdk/http_errors_test.go
Currently, If the server returns a JSON error, we'll decode it into `sdk.APIErrors` and fail silently if it was a different type of JSON, producing an empty `sdk.APIErrors` struct.
`sdk.Client` will not correctly handle JSON errors other than `sdk.APIErrors`.
=> fix: Correct API errors handling

.github/renovate.json5
=> chore: Add allowedCommands to renovate

manifest/v1alpha/agent/examples/sumo-logic.yaml, manifest/v1alpha/data_sources.go, manifest/v1alpha/direct/examples/sumo-logic.yaml, manifest/v1alpha/slo/metrics_sumo_logic.go, manifest/v1alpha/slo/metrics_sumo_logic_test.go
SumoLogic now supports Replay and SLI Analysis features (beta Agent/Direct only).
=> feat: add SumoLogic to data retrieval max duration mappings (#776)
